### ISSUE TITLE
/boxes/{box_id}?format=long

### ISSUE THREAD

**Issue by jasgan** [Subberbox/Subber-api#54]
For "short_desc" in JSON, it returns a string with some words stuck to each other. For box_id = 3, "short_desc": "Bocandy is a Candy Subscription Box from Around the World for just $15/month.Each month, we send you a box full of candywith cool info about where it came from."

"$15/month.Each" and "candywith" are stuck to each other.

**Comment by hhanesand** [comment]
Isn't this just a database error?

**Comment by jasgan** [comment]
I checked the database and the short_desc seems to be formatted correctly.

**Comment by hhanesand** [comment]
well that sure is strange... thanks for reporting!

**Comment by jasgan** [comment]
np!!

**Comment by hhanesand** [comment]
non breaking spaces lol
