### ISSUE TITLE
Shipping Endpoint

### ISSUE THREAD

**Issue by jasgan** [Subberbox/Subber-api#59]
1)  Could you create an endpoint for returning the shipping details for a specific shipping_id?
e.g. /customers?type[]=shipping&id=19(shipping_id)
2) How do I update the shipping details for a specific shipping_id?

**Comment by hhanesand** [comment]
There's and endpoint for getting the shipping information at /shipping where you can post get modify and delete.

Is it in your postman?

**Comment by jasgan** [comment]
I only have "get/del/post" in Postman and no "patch".

**Comment by jasgan** [comment]
Also, is there a "DEL" for "Stripe" and "Orders"?

**Comment by hhanesand** [comment]
ok for shipping there should be an update

there is no del for stripe yet and neither from orders

**Comment by jasgan** [comment]
When I try updating shipping, I get an error:

{
  "error": true,
  "message": "Page not found"
}

**Comment by hhanesand** [comment]
its not implemented yet, will do soon

**Comment by jasgan** [comment]
Ok sounds good! And do you think you could prioritize GitHub Issue #55? I'd like to wrap up the vendor dashboard so I can start e-mailing vendors to register an account.

**Comment by jasgan** [comment]
When I try updating shipping it gives a duplicate entry error:
{
  "error": true,
  "message": "Error execute(\"Duplicate entry \\'76\\' for key \\'PRIMARY\\'\")"
}

I ran:
http://{{SERVER}}/shipping/76?default=true

**Comment by hhanesand** [comment]
fixed
