### ISSUE TITLE
/orders?fulfilled={boolean}

### ISSUE THREAD

**Issue by jasgan** [Subberbox/Subber-api#67]
**Could you return a "short" JSON version with:**

(1) Order Reference ID Number, 
(2) Customer's Name, 
(3) Box Name, 
(4) Date, 
(5) Box Price

**And a "long" JSON version with:** 

Array of:
(1) Order Reference ID Number ok
(2) Box Name,ok
(3) Box Price,ok
(4) Taxes, ???? 
(5) Total Paid by customer ????

Array of:
(6) Customer Name, ok
(7) Customer E-mail, ok
(8) Customer Shipping Address, ok
(9) Customer Billing Address ????

Array of:
(10) Time order was placed

**Comment by hhanesand** [comment]
everything but taxes is done
