### ISSUE TITLE
{"error":true,"message":"Invalid request"}

### ISSUE THREAD

**Issue by jasgan** [Subberbox/Subber-api#68]
New customer --> First Order --> "http://api.instacrate.me/subscriptions" --> {"error":true,"message":"Invalid request"}

**Comment by jasgan** [comment]
UPDATE: {"error":true,"message":"Error error(\"invalid_request_error\", \"No such plan: 54A50EEA-92D2-4391-8BCA-EE956806923E\")"}

**Comment by hhanesand** [comment]
fixed
