### ISSUE TITLE
Get 1 vendor box info based on box_id

### ISSUE THREAD

**Issue by jasgan** [Subberbox/Subber-api#76]
http://{{SERVER}}/boxes?format=short&type=vendor

Could we append &id=XX to get the box information for 1 box?

**Comment by hhanesand** [comment]
why not use `GET /boxes/{id}` ?

do you need the type=vendor support?

**Comment by jasgan** [comment]
Yeah i think so - that way  the vendor can edit the box?

**Comment by hhanesand** [comment]
If you just need to fetch the box and you already have the id `GET /boxes/{id}` should work fine

If you need to modify, use `PATCH /boxes/{id}`

am i missing anything?

**Comment by jasgan** [comment]
Oh that is true, I forgot about that endpoint haha
