### ISSUE TITLE
PATCH /boxes/1

### ISSUE THREAD

**Issue by jasgan** [Subberbox/Subber-api#79]
{
  "error": true,
  "message": "Method PATCH is not allowed on resource Box(1) by this user. Must be logged in as Vendor(1)."
}

Got this error even though authenticated as the vendor for this box.

**Comment by hhanesand** [comment]
remnants of the double log in bug - fixed

**Comment by jasgan** [comment]
I sent a JSON with changes via Postman and received this message:

{
  "error": true,
  "message": "Invalid request"
}

**Comment by hhanesand** [comment]
What was the post body?

**Comment by jasgan** [comment]
It was the body sample in Postman.

**Comment by jasgan** [comment]
I also tried {Name: "New Name"} only and it gave the same error

**Comment by hhanesand** [comment]
fixed
